spring:
  cloud:
    gateway:
      routes:
        - id: student-server
          uri: http://localhost:8020
          predicates:
            - Path=/students/**
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/iit
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
          client-id: iit-delhi
          client-secret: P5QheuLDTzUwglVDqvV3SFeZKEWmYrQB

server:
  port: 9090